### PR TITLE
Add support for changing a messages visibility timeout.

### PR DESCRIPTION
**Pull request by jmoseley**

### CODE REVIEW

**Comment by stkem** [comment]
:+1:

**Comment by jmoseley** [comment]
What is the schedule for this being available in a release?

**Comment by stkem** [comment]
There isn't really a release schedule, but we'll try to get something out in the next few days. Bug me if that doesn't happen.

**Comment by jmoseley** [comment]
Sounds great. Thanks.

**Comment by jmoseley** [comment]
Hey sorry to bug you again, any chance of getting this released?

**Comment by jmoseley** [comment]
@stkem Bump.

**Comment by jmoseley** [comment]
@stkem Did you have a chance to push this out?

**Comment by leogrim** [comment]
@jmoseley @stkem just released 0.3.14!

**Comment by jmoseley** [comment]
:+1: thanks guys.

**Pull request merged**
